### ISSUE TITLE
System.FormatException when parse "start" datetime

### ISSUE THREAD

**Issue by ninhnguyentrac** [episerver/content-ab-testing#24]
Detail:
![image](https://user-images.githubusercontent.com/20015282/219602715-cc4e44ee-6317-4ffc-8cbb-eb2a3f1ce1b6.png)

Cause:
when saving "start" is saved as CultureInfo.InvariantCulture
when parsing "start" using DateTime.Parse which using System.Threading.Thread.CurrentThread.CurrentCulture to parse data
current System.Threading.Thread.CurrentThread.CurrentCulture when exception is "pt-BR".

**Comment by hungoptimizely** [comment]
This issue has been reported as a bug. Thanks!
