### ISSUE TITLE
Cannot start a test in CMS UI 12.19.0

### ISSUE THREAD

**Issue by linhdoan** [episerver/content-ab-testing#30]
The newest package doesn't work with CMS UI 12.19.0 due to the file "Shell/12.19.0/ClientResources/epi/shell/widgets.js" in latest UI package overridden the put method with a Xhr Http Post:

![image](https://github.com/episerver/content-ab-testing/assets/17606907/d5e4992b-a03a-4e7e-bbb7-b4f40f805a37)

This lead to a 405 http status code (Method not Allowed) due to the rest controller only support GET & PUT

**Comment by richardstrom** [comment]
It's the same as you mention in version 12.17.1 (Just ran into this problem myself)

**Comment by AgentLintZeal** [comment]
We are having the same issue. I tried downloading the repo and changing the Put to a Post in KpiStore lines 52 & 53, but I cannot get the initiailzation to work when I reference the testing.web project from my Opti instance.  I tried packing to make a local nuget package, but there are some files missing that prevents me from making the package.

Is there a way to test locally with my own branch and still have the UI setup the code for editing?

**Comment by TPofahl** [comment]
I also have the same issue, using cms 12.18, using "EPiServer.Marketing.Testing" version 3.1.1. I also reported the issue here:
https://world.optimizely.com/forum/developer-forum/Problems-and-bugs/Thread-Container/2023/7/abtesting--kpi-error-in-cms-12----method-not-allowed/

**Comment by hungoptimizely** [comment]
This issue has been fixed in the latest version.
